import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ChatbotSidebar from "/ChatbotSidebar"; // Make sure this path is correct for your project structure

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Correct favicon path */}
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <ChatbotSidebar /> {/* Keeping this as is */}
      </body>
    </html>
  );
}
